# Generated by Django 5.0.6 on 2024-06-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='TaskModel',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='task',
            new_name='task_name',
        ),
    ]
